### ISSUE TITLE
not working with Kocher's examples

### ISSUE THREAD

**Issue by canertol** [0xADE1A1DE/USLH#1]
Hi,

I installed the modified LLVM version from the Zenodo link and tried it on OpenSSL examples. It successfully shows ```Found in --> ``` in many functions. 
However, when I try it to compile and fix[ these Spectre v1 examples](https://github.com/PLSysSec/pitchfork-angr/blob/master/new-testcases/spectrev1.c), originally from Paul Kocher, it neither finds any of them as a Spectre gadget nor fixes them.

Is this expected, or am I doing something wrong? Have you tested them on these examples?

**Comment by Neo-Outis** [comment]
Hi, I had a quick look at the code you paste. I think case_10 is under the definition of the gadget with the paper.
The code for gadget search present in the repo is quite strict on the definition of gadget and I exclude all livein MIRs that involve memory access (Because they *may* conflict with the constant-time).

To relax the definition a bit, you can comment the code at https://github.com/0xADE1A1DE/USLH/blob/fdb558f3a38150564839903da059ba4e378e8702/LLVM_FIX/X86MIRanalyze.cpp#L177

which will abort the search if a MIR related to a livein is marked as accessing memory.

After I comment this condition, the tool can find the gadget with -O1 optimisation.
A result on my machine is attached.



<img width="928" alt="github-issue1" src="https://github.com/0xADE1A1DE/USLH/assets/56351003/fb0c2ecc-19c7-4610-996c-312afb49523b">

You could further uncomment the code at 
https://github.com/0xADE1A1DE/USLH/blob/fdb558f3a38150564839903da059ba4e378e8702/LLVM_FIX/X86MIRanalyze.cpp#L111

to see the Machine IR.

Note that the pass is running at the Machine IR level, so some optimisation has already been applied before this pass. It means that the MIR you see could be very different from the original C code.

**Comment by Neo-Outis** [comment]
If you would like to attend the code for your own usage. You could keep the code that find conditional branches (which does a bit more than it) and livein analysis (track the propagation of inputs). The other part of the code is basically serving for finding the gadget defined in the paper. And they can be easily changed with the code serves for your own purposes.

Please don't hesitate in contacting me for further questions or discussions. 
Or you could email me directly (zhiyuanz5@student.unimelb.edu.au) ; )
